# Generated by Django 2.1.3 on 2018-12-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_dration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='dration',
            field=models.IntegerField(default=0),
        ),
    ]
